apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-k8s-webserver
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: simple-k8s-webserver
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9360"
      labels:
        app: simple-k8s-webserver
    spec:
      containers:
      - name: simple-k8s-webserver
        image: spangen/simple-k8s-webserver:latest
          # We would normally just pull if not IfNotPresent
          # but as we're using latest, let's always pull
        imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: http-metrics
          containerPort: 9360
          protocol: TCP
        command:
        - ./simple-k8s-webserver
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
