apiVersion: v1
kind: Service
metadata:
  name: simple-k8s-webserver
spec:
  type: ClusterIP
  selector:
    app: simple-k8s-webserver
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
