name: Docker Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USER}}
      DOCKER_REPO: ${{ github.event.repository.name }}
      DOCKER_TAG: latest
      DOCKER_CACHE: buildcache
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER}}
          password: ${{ secrets.DOCKER_HUB_READ_WRITE }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
          cache-from: type=registry,ref=${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_CACHE }}
          cache-to: type=registry,ref=${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_CACHE }},mode=max
      # TODO
      # Set up a versioning scheme, e.g. with
      # https://github.com/docker/metadata-action
      # https://github.com/marketplace/actions/git-semantic-version
